---
- hosts: rhm-x3550-13.rhm.lab.eng.bos.redhat.com
  become: true
  tasks:
    - name: Make sure we can connect
      ping:
    - name: Install emacs, git
      yum: name={{item}}
      with_items:
        - emacs
        - git
    - name: Install devel dependencies
      yum: name={{item}}
      with_items:
        - epel-release
    - name: install the "Development tools' package group
      yum:
        name: "@Development tools"
        state: present
    - name: Install python and pip stuff
      yum: name={{item}}
      with_items:
        - python-pip
        - python-wheel
        - python-tox
        - libffi-devel
    - name: update pip
      shell: >
        pip install --upgrade setuptools tox cffi
    - name: upgrade all packages
      yum: 
        name: '*'
        state: latest

