---
- hosts: rhm-per530-01.rhm.lab.eng.bos.redhat.com
  become: true
  vars:
    createuser: 'osdeploy'
    createpassword: 'password'
  tasks:
    - name: Make sure we can connect
      ping:
    - name: Setup createuser
      user:
        name: '{{ createuser }}'
        password: '{{ createpassword }}'
        generate_ssh_key: yes
    - name: Sudoers | update sudoers file and validate
      lineinfile: "dest=/etc/sudoers
        insertafter=EOF
        line='{{ createuser }} ALL=(ALL) NOPASSWD: ALL'
        regexp='{{ createuser }} ALL=(ALL) NOPASSWD: ALL'
        state=present"
    - name: Setup | authorized key upload
      authorized_key:
        user: root
        key: "{{ lookup('file', '/home/{{ createuser }}/.ssh/id_rsa.pub') }}"
        state: present
        path: '/root/.ssh/authorized_keys'
        manage_dir: yes
